Pin rusoto to 0.42 on jobsrv
0.43 requires Futures to also be unpinned. When using Futures 0.3 in jobsrv,
the s3 log archiver implementation requires the trait functions be made async
which is not supported at this time.

error[E0706]: trait fns cannot be declared `async`

Signed-off-by: Scott Macfarlane <smacfarlane@chef.io>